#!/bin/bash
#
#
# Kontrollib Apache olemasolu
APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")
# kui apache on installitud siis v2ljastatab teate. Kui ei, siis installitakse.
if [ $APACHE2 -eq 0 ]; then
	echo "Apache2 paigaldamine."
	sudo apt-get install -y apache2;
elif [ $APACHE2 -eq 1 ]; then
	echo "Apache2 on paigaldatud"
	sudo service apache2 status
fi
