#!/bin/bash
#
#
sql=$(dpkg-query -W -f='${Status}' mysql 2>/dev/null | grep -c "ok installed")
if [ $sql -eq 0 ]; then
	echo "Mysql paigaldamine"
	sudo apt-get install -y mysql-server;
elif [$sql -eq 1]; then
	echo "Mysql on paigaldatud"
	sudo service mysql status
fi
